name: Update README.md

on:
  schedule:
    - cron: '0 * * * *'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Generate README.md
      uses: actions-js/profile-readme@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        username: William5553
        template: "TEMPLATE.md"


    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
